### ISSUE TITLE
Cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by SXRWahrheit** [ledesmablt/spotify-cli#23]
Sorry, GitHub sent the issue before I finished writing it.

I installed Python 3.10 and used PIP to install spotify-cli. Upon attempting to auth I get the following output:

```C:\Users\matti>spotify auth login
You used a custom Client ID and secret to authenticate last time. Use these again?
(Type "n" to revert to the default ID and secret) [Y/n]: Y
Traceback (most recent call last):
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\Scripts\spotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\cli\commands\auth.py", line 65, in login
    from PyInquirer import prompt
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)```

**Comment by SXRWahrheit** [comment]
Switching to Python 3.9 as suggested by friends yielded the return of the issue in #22.

**Comment by SXRWahrheit** [comment]
I was able to fix the path issue for 3.9 but am getting an issue about a missing zlib DLL and have been unable to find anything to provide that installation that works on Windows 11.

**Comment by ledesmablt** [comment]
Hi @SXRWahrheit thanks for raising this issue. The error traceback you sent suggests that a dependency of the [PyInquirer package](https://github.com/CITGuru/PyInquirer) is causing the bug, which seems to be a [breaking change introduced in python 3.10](https://stackoverflow.com/a/70557518).

I'm running python 3.8 on mac, maybe you could try installing 3.8 on your system and see if it works? Apologies as I'm not able to provide support for problems specific to windows 11.

I'll see if i can rework the CLI such that it won't rely on PyInquirer, but that might take some time. I suggest trying another python version in the meantime.

**Comment by hugeblank** [comment]
For those on linux experiencing this issue I've got a bit of a bodge fix that doesn't involve any sort of installing of older python versions. Looking at the error log provided in the first post, the third to last line has the path that you want. For the reporter:
```
File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
```
and for me, and most likely you, something like:
```
File "/home/hugeblank/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
```

This command replaces the problematic line with the patched one, as outlined in @ledesmablt's comment:
```zsh
sed -i -e 's/from collections import Mapping/from collections.abc import Mapping/' <PATH HERE>
```
So for me, I take the path that that third to last line outputs and drop it into the script:
```zsh
sed -i -e 's/from collections import Mapping/from collections.abc import Mapping/' ~/.local/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py
```
Try `spotify auth login` or whatever the command you were trying to use again, should work! I don't know if this persists on an upgrade, and if it doesn't, hopefully the next update fixes the issue and this will be a moot warning.
